### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by bsouhaib** [meowoodie/Spatio-Temporal-Point-Process-Simulator#1]
Hi,

I can't find data   = ('../Spatio-Temporal-Point-Process-Simulator/data/apd.crime.perday.npy') and 
 ('../Spatio-Temporal-Point-Process-Simulator/data/gaussian_mixture_params.npz').

Any help on this?

Thanks.

**Comment by meowoodie** [comment]
Hi bsouhaib,

Sorry for the late reply, the crime data is under a nondisclosure agreement with APD. You can definitely try this on other dataset. 

Thank you very much for your interest.
