### ISSUE TITLE
Where is the data?

### ISSUE THREAD

**Issue by JasonNerd** [meowoodie/Spatio-Temporal-Point-Process-Simulator#2]
Umm, now I am trying to understand this code, however, I cannot see the data. Would you please upload the data like 
`data/eventos_desagregados.csv`
`data/rescale.ambulance.perday.npy` 
etc.
and thanks so much.

**Comment by meowoodie** [comment]
Thank you for your interest. Unfortunately, these data are not publicly available now. Please feel free to generate synthetic data by following the toy example in README.md.

**Comment by RichardShea** [comment]
Hi,

Which of those files can I replicate Figures 3,4,5, and 6?

Thank you,

-Richard
