### ISSUE TITLE
Is there anything similar in R?

### ISSUE THREAD

**Issue by Koroxal** [meowoodie/Spatio-Temporal-Point-Process-Simulator#3]
I was wondering if there is a code in R to simulate Hawkes process. Thanks

**Comment by meowoodie** [comment]
Thanks for your interest. This is what I found in R: https://cran.r-project.org/web/packages/hawkes/hawkes.pdf

Hope this could be of some help.

**Comment by Koroxal** [comment]
Thanks but I'm not sure that that's spatio-temporal Hawkes process.

**Comment by meowoodie** [comment]
To the best of my knowledge, there is no easy-to-use package available for simulating spatio-temporal Hawkes process, which is why I intended to develop my own simulator in Python.

**Comment by Koroxal** [comment]
Thank you for your response! I have another doubt, how to set a maximum to the thinning            i

if lam_value <= D * lam_bar:

lam_bar should be a maximum of function kernel. I'm using exponential kernel, so how to set this upper limit? 

Thank you in advance!

**Comment by meowoodie** [comment]
One of simplest but inefficient way is to set it as a constant.

Otherwise, please see Algorithm 3 in the appendix: https://openreview.net/pdf?id=0rcbOaoBXbg
