### ISSUE TITLE
Missing class in stppg

### ISSUE THREAD

**Issue by nick3703** [meowoodie/Spatio-Temporal-Point-Process-Simulator#4]
Hi, thanks for your work on this! 

Your .readme references includes:

stppg import StdDiffusionKernel, HawkesLam, MarkedSpatialTemporalPointProcess

However there does not appear to be a 'MarkedSpatialTemporalPointProcess' class within stppg.

**Comment by meowoodie** [comment]
Hi,

Thanks for the issue. `MarkedSpatialTemporalPointProcess` now has been removed. You can use the existing `SpatialTemporalPointProcess` to implement marked spatial temporal point process by setting the dimension of `S` larger than 2. 

Thanks,
Woody
